# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sniperGui.ui'
#
# Created: Fri Nov  8 11:17:45 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(909, 782)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 450))
        self.tabWidget.setStyleSheet(_fromUtf8("QGroupBox  {\n"
"\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"    font-weight: bold\n"
"}\n"
" \n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.connectionTab = QtGui.QWidget()
        self.connectionTab.setObjectName(_fromUtf8("connectionTab"))
        self.gridLayout = QtGui.QGridLayout(self.connectionTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 276, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.localIPBox = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localIPBox.sizePolicy().hasHeightForWidth())
        self.localIPBox.setSizePolicy(sizePolicy)
        self.localIPBox.setMinimumSize(QtCore.QSize(200, 0))
        self.localIPBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.localIPBox.setObjectName(_fromUtf8("localIPBox"))
        self.horizontalLayout_2.addWidget(self.localIPBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.localPortBox = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localPortBox.sizePolicy().hasHeightForWidth())
        self.localPortBox.setSizePolicy(sizePolicy)
        self.localPortBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.localPortBox.setObjectName(_fromUtf8("localPortBox"))
        self.horizontalLayout_2.addWidget(self.localPortBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(450, 100))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.targetIPBox = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetIPBox.sizePolicy().hasHeightForWidth())
        self.targetIPBox.setSizePolicy(sizePolicy)
        self.targetIPBox.setMinimumSize(QtCore.QSize(200, 0))
        self.targetIPBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.targetIPBox.setObjectName(_fromUtf8("targetIPBox"))
        self.horizontalLayout_3.addWidget(self.targetIPBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.targetPortBox = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetPortBox.sizePolicy().hasHeightForWidth())
        self.targetPortBox.setSizePolicy(sizePolicy)
        self.targetPortBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.targetPortBox.setObjectName(_fromUtf8("targetPortBox"))
        self.horizontalLayout_3.addWidget(self.targetPortBox)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.connectButton = QtGui.QPushButton(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(100, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("network-wired"))
        self.connectButton.setIcon(icon)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.horizontalLayout_14.addWidget(self.connectButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.disconnectButton = QtGui.QPushButton(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        self.disconnectButton.setMinimumSize(QtCore.QSize(100, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("network-offline"))
        self.disconnectButton.setIcon(icon)
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.horizontalLayout_14.addWidget(self.disconnectButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(373, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.connectionTab, _fromUtf8(""))
        self.controlTab = QtGui.QWidget()
        self.controlTab.setEnabled(False)
        self.controlTab.setObjectName(_fromUtf8("controlTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.controlTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.addButton = QtGui.QToolButton(self.controlTab)
        self.addButton.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.addButton.setIcon(icon)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout_3.addWidget(self.addButton, 1, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.loadCfgButton = QtGui.QPushButton(self.controlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadCfgButton.sizePolicy().hasHeightForWidth())
        self.loadCfgButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.loadCfgButton.setIcon(icon)
        self.loadCfgButton.setObjectName(_fromUtf8("loadCfgButton"))
        self.horizontalLayout_13.addWidget(self.loadCfgButton)
        self.saveCfgButton = QtGui.QPushButton(self.controlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveCfgButton.sizePolicy().hasHeightForWidth())
        self.saveCfgButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.saveCfgButton.setIcon(icon)
        self.saveCfgButton.setObjectName(_fromUtf8("saveCfgButton"))
        self.horizontalLayout_13.addWidget(self.saveCfgButton)
        spacerItem5 = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.sendButton = QtGui.QPushButton(self.controlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-send"))
        self.sendButton.setIcon(icon)
        self.sendButton.setObjectName(_fromUtf8("sendButton"))
        self.horizontalLayout_13.addWidget(self.sendButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.configFileLabel = QtGui.QLabel(self.controlTab)
        self.configFileLabel.setObjectName(_fromUtf8("configFileLabel"))
        self.gridLayout_3.addWidget(self.configFileLabel, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 288, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 4, 1, 1, 1)
        self.removeButton = QtGui.QToolButton(self.controlTab)
        self.removeButton.setMinimumSize(QtCore.QSize(40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.removeButton.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removeButton.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.removeButton.setIcon(icon)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.gridLayout_3.addWidget(self.removeButton, 2, 1, 1, 1)
        self.clearButton = QtGui.QToolButton(self.controlTab)
        self.clearButton.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.clearButton.setIcon(icon)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.gridLayout_3.addWidget(self.clearButton, 3, 1, 1, 1)
        self.configView = QtGui.QTableView(self.controlTab)
        self.configView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.configView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.configView.setSortingEnabled(True)
        self.configView.setCornerButtonEnabled(False)
        self.configView.setObjectName(_fromUtf8("configView"))
        self.configView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.configView, 1, 0, 4, 1)
        self.tabWidget.addTab(self.controlTab, _fromUtf8(""))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setEnabled(True)
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.dataTab)
        self.gridLayout_8.setSpacing(12)
        self.gridLayout_8.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.dataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setStyleSheet(_fromUtf8("QGroupBox  {\n"
"\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"    font-weight: bold\n"
"}\n"
" \n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.triggerButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerButton.sizePolicy().hasHeightForWidth())
        self.triggerButton.setSizePolicy(sizePolicy)
        self.triggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.triggerButton.setObjectName(_fromUtf8("triggerButton"))
        self.horizontalLayout_4.addWidget(self.triggerButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.numTriggerBox = QtGui.QLineEdit(self.groupBox_5)
        self.numTriggerBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numTriggerBox.sizePolicy().hasHeightForWidth())
        self.numTriggerBox.setSizePolicy(sizePolicy)
        self.numTriggerBox.setMinimumSize(QtCore.QSize(0, 20))
        self.numTriggerBox.setInputMask(_fromUtf8(""))
        self.numTriggerBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numTriggerBox.setObjectName(_fromUtf8("numTriggerBox"))
        self.horizontalLayout_6.addWidget(self.numTriggerBox)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(222, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.captureButton = QtGui.QPushButton(self.groupBox_5)
        self.captureButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.captureButton.sizePolicy().hasHeightForWidth())
        self.captureButton.setSizePolicy(sizePolicy)
        self.captureButton.setMinimumSize(QtCore.QSize(0, 15))
        self.captureButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.captureButton.setAutoFillBackground(False)
        self.captureButton.setCheckable(True)
        self.captureButton.setDefault(False)
        self.captureButton.setObjectName(_fromUtf8("captureButton"))
        self.horizontalLayout.addWidget(self.captureButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.sendTriggerButton = QtGui.QPushButton(self.groupBox_5)
        self.sendTriggerButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendTriggerButton.sizePolicy().hasHeightForWidth())
        self.sendTriggerButton.setSizePolicy(sizePolicy)
        self.sendTriggerButton.setMinimumSize(QtCore.QSize(150, 30))
        self.sendTriggerButton.setMaximumSize(QtCore.QSize(150, 30))
        self.sendTriggerButton.setObjectName(_fromUtf8("sendTriggerButton"))
        self.horizontalLayout_9.addWidget(self.sendTriggerButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.dataTab)
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox  {\n"
"\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"    font-weight: bold\n"
"}\n"
" \n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.clearBufferButton = QtGui.QPushButton(self.groupBox_3)
        self.clearBufferButton.setObjectName(_fromUtf8("clearBufferButton"))
        self.gridLayout_7.addWidget(self.clearBufferButton, 5, 0, 1, 1)
        self.currFileLCD = QtGui.QLCDNumber(self.groupBox_3)
        self.currFileLCD.setMinimumSize(QtCore.QSize(100, 20))
        self.currFileLCD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.currFileLCD.setFrameShape(QtGui.QFrame.Box)
        self.currFileLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.currFileLCD.setSmallDecimalPoint(False)
        self.currFileLCD.setNumDigits(10)
        self.currFileLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.currFileLCD.setObjectName(_fromUtf8("currFileLCD"))
        self.gridLayout_7.addWidget(self.currFileLCD, 3, 0, 1, 1)
        self.numEventsLCD = QtGui.QLCDNumber(self.groupBox_3)
        self.numEventsLCD.setMinimumSize(QtCore.QSize(100, 20))
        self.numEventsLCD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.numEventsLCD.setFrameShape(QtGui.QFrame.Box)
        self.numEventsLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.numEventsLCD.setSmallDecimalPoint(False)
        self.numEventsLCD.setNumDigits(10)
        self.numEventsLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.numEventsLCD.setObjectName(_fromUtf8("numEventsLCD"))
        self.gridLayout_7.addWidget(self.numEventsLCD, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 39, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem12, 4, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 3, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.dataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox  {\n"
"\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"    font-weight: bold\n"
"}\n"
" \n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(12)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.tagBox = QtGui.QLineEdit(self.groupBox_4)
        self.tagBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagBox.sizePolicy().hasHeightForWidth())
        self.tagBox.setSizePolicy(sizePolicy)
        self.tagBox.setMinimumSize(QtCore.QSize(0, 0))
        self.tagBox.setSizeIncrement(QtCore.QSize(4, 0))
        self.tagBox.setObjectName(_fromUtf8("tagBox"))
        self.horizontalLayout_8.addWidget(self.tagBox)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.triggerPerFileBox = QtGui.QLineEdit(self.groupBox_4)
        self.triggerPerFileBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerPerFileBox.sizePolicy().hasHeightForWidth())
        self.triggerPerFileBox.setSizePolicy(sizePolicy)
        self.triggerPerFileBox.setMinimumSize(QtCore.QSize(0, 0))
        self.triggerPerFileBox.setSizeIncrement(QtCore.QSize(4, 0))
        self.triggerPerFileBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.triggerPerFileBox.setObjectName(_fromUtf8("triggerPerFileBox"))
        self.horizontalLayout_10.addWidget(self.triggerPerFileBox)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_10)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.autoSaveCB = QtGui.QCheckBox(self.groupBox_4)
        self.autoSaveCB.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoSaveCB.sizePolicy().hasHeightForWidth())
        self.autoSaveCB.setSizePolicy(sizePolicy)
        self.autoSaveCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.autoSaveCB.setChecked(False)
        self.autoSaveCB.setObjectName(_fromUtf8("autoSaveCB"))
        self.horizontalLayout_17.addWidget(self.autoSaveCB)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_16.addWidget(self.label_8)
        self.startButton = QtGui.QPushButton(self.groupBox_4)
        self.startButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(0, 15))
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setCheckable(True)
        self.startButton.setDefault(False)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_16.addWidget(self.startButton)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chDirButton = QtGui.QPushButton(self.groupBox_4)
        self.chDirButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chDirButton.sizePolicy().hasHeightForWidth())
        self.chDirButton.setSizePolicy(sizePolicy)
        self.chDirButton.setObjectName(_fromUtf8("chDirButton"))
        self.horizontalLayout_11.addWidget(self.chDirButton)
        self.clearDataButton = QtGui.QPushButton(self.groupBox_4)
        self.clearDataButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearDataButton.sizePolicy().hasHeightForWidth())
        self.clearDataButton.setSizePolicy(sizePolicy)
        self.clearDataButton.setObjectName(_fromUtf8("clearDataButton"))
        self.horizontalLayout_11.addWidget(self.clearDataButton)
        self.chFileButton = QtGui.QPushButton(self.groupBox_4)
        self.chFileButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chFileButton.sizePolicy().hasHeightForWidth())
        self.chFileButton.setSizePolicy(sizePolicy)
        self.chFileButton.setObjectName(_fromUtf8("chFileButton"))
        self.horizontalLayout_11.addWidget(self.chFileButton)
        self.filenameLabel = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameLabel.sizePolicy().hasHeightForWidth())
        self.filenameLabel.setSizePolicy(sizePolicy)
        self.filenameLabel.setSizeIncrement(QtCore.QSize(10, 0))
        self.filenameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filenameLabel.setScaledContents(True)
        self.filenameLabel.setWordWrap(True)
        self.filenameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.filenameLabel.setObjectName(_fromUtf8("filenameLabel"))
        self.horizontalLayout_11.addWidget(self.filenameLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.calibCB = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.calibCB.setFont(font)
        self.calibCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.calibCB.setObjectName(_fromUtf8("calibCB"))
        self.horizontalLayout_18.addWidget(self.calibCB)
        self.cFileButton = QtGui.QPushButton(self.groupBox_4)
        self.cFileButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cFileButton.sizePolicy().hasHeightForWidth())
        self.cFileButton.setSizePolicy(sizePolicy)
        self.cFileButton.setObjectName(_fromUtf8("cFileButton"))
        self.horizontalLayout_18.addWidget(self.cFileButton)
        self.cFileLabel = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cFileLabel.sizePolicy().hasHeightForWidth())
        self.cFileLabel.setSizePolicy(sizePolicy)
        self.cFileLabel.setSizeIncrement(QtCore.QSize(10, 0))
        self.cFileLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cFileLabel.setScaledContents(True)
        self.cFileLabel.setWordWrap(True)
        self.cFileLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.cFileLabel.setObjectName(_fromUtf8("cFileLabel"))
        self.horizontalLayout_18.addWidget(self.cFileLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.gridLayout_8.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.graphBox = QtGui.QGroupBox(self.dataTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphBox.sizePolicy().hasHeightForWidth())
        self.graphBox.setSizePolicy(sizePolicy)
        self.graphBox.setMinimumSize(QtCore.QSize(0, 0))
        self.graphBox.setStyleSheet(_fromUtf8("QGroupBox  {\n"
"\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"    font-weight: bold\n"
"}\n"
" \n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}"))
        self.graphBox.setCheckable(False)
        self.graphBox.setObjectName(_fromUtf8("graphBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.graphBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.drawButton = QtGui.QPushButton(self.graphBox)
        self.drawButton.setObjectName(_fromUtf8("drawButton"))
        self.gridLayout_5.addWidget(self.drawButton, 0, 4, 1, 1)
        self.browseButton = QtGui.QPushButton(self.graphBox)
        self.browseButton.setEnabled(True)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.gridLayout_5.addWidget(self.browseButton, 1, 4, 1, 1)
        self.showMarkCB = QtGui.QCheckBox(self.graphBox)
        self.showMarkCB.setEnabled(True)
        self.showMarkCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showMarkCB.setChecked(True)
        self.showMarkCB.setObjectName(_fromUtf8("showMarkCB"))
        self.gridLayout_5.addWidget(self.showMarkCB, 2, 3, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.allONButton = QtGui.QPushButton(self.graphBox)
        self.allONButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.allONButton.setObjectName(_fromUtf8("allONButton"))
        self.horizontalLayout_12.addWidget(self.allONButton)
        self.allOFFButton = QtGui.QPushButton(self.graphBox)
        self.allOFFButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.allOFFButton.setObjectName(_fromUtf8("allOFFButton"))
        self.horizontalLayout_12.addWidget(self.allOFFButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 8, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 9, 5, 1, 1)
        self.chLayout = QtGui.QGridLayout()
        self.chLayout.setHorizontalSpacing(10)
        self.chLayout.setVerticalSpacing(1)
        self.chLayout.setObjectName(_fromUtf8("chLayout"))
        self.ch10 = QtGui.QCheckBox(self.graphBox)
        self.ch10.setObjectName(_fromUtf8("ch10"))
        self.chLayout.addWidget(self.ch10, 2, 1, 1, 1)
        self.ch0 = QtGui.QCheckBox(self.graphBox)
        self.ch0.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch0.setObjectName(_fromUtf8("ch0"))
        self.chLayout.addWidget(self.ch0, 0, 0, 1, 1)
        self.ch8 = QtGui.QCheckBox(self.graphBox)
        self.ch8.setObjectName(_fromUtf8("ch8"))
        self.chLayout.addWidget(self.ch8, 0, 1, 1, 1)
        self.ch1 = QtGui.QCheckBox(self.graphBox)
        self.ch1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch1.setObjectName(_fromUtf8("ch1"))
        self.chLayout.addWidget(self.ch1, 1, 0, 1, 1)
        self.ch9 = QtGui.QCheckBox(self.graphBox)
        self.ch9.setObjectName(_fromUtf8("ch9"))
        self.chLayout.addWidget(self.ch9, 1, 1, 1, 1)
        self.ch2 = QtGui.QCheckBox(self.graphBox)
        self.ch2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch2.setObjectName(_fromUtf8("ch2"))
        self.chLayout.addWidget(self.ch2, 2, 0, 1, 1)
        self.ch3 = QtGui.QCheckBox(self.graphBox)
        self.ch3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch3.setObjectName(_fromUtf8("ch3"))
        self.chLayout.addWidget(self.ch3, 3, 0, 1, 1)
        self.ch11 = QtGui.QCheckBox(self.graphBox)
        self.ch11.setObjectName(_fromUtf8("ch11"))
        self.chLayout.addWidget(self.ch11, 3, 1, 1, 1)
        self.ch4 = QtGui.QCheckBox(self.graphBox)
        self.ch4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch4.setObjectName(_fromUtf8("ch4"))
        self.chLayout.addWidget(self.ch4, 4, 0, 1, 1)
        self.ch12 = QtGui.QCheckBox(self.graphBox)
        self.ch12.setObjectName(_fromUtf8("ch12"))
        self.chLayout.addWidget(self.ch12, 4, 1, 1, 1)
        self.ch5 = QtGui.QCheckBox(self.graphBox)
        self.ch5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch5.setObjectName(_fromUtf8("ch5"))
        self.chLayout.addWidget(self.ch5, 5, 0, 1, 1)
        self.ch13 = QtGui.QCheckBox(self.graphBox)
        self.ch13.setObjectName(_fromUtf8("ch13"))
        self.chLayout.addWidget(self.ch13, 5, 1, 1, 1)
        self.ch6 = QtGui.QCheckBox(self.graphBox)
        self.ch6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch6.setObjectName(_fromUtf8("ch6"))
        self.chLayout.addWidget(self.ch6, 6, 0, 1, 1)
        self.ch14 = QtGui.QCheckBox(self.graphBox)
        self.ch14.setObjectName(_fromUtf8("ch14"))
        self.chLayout.addWidget(self.ch14, 6, 1, 1, 1)
        self.ch7 = QtGui.QCheckBox(self.graphBox)
        self.ch7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch7.setObjectName(_fromUtf8("ch7"))
        self.chLayout.addWidget(self.ch7, 7, 0, 1, 1)
        self.ch15 = QtGui.QCheckBox(self.graphBox)
        self.ch15.setObjectName(_fromUtf8("ch15"))
        self.chLayout.addWidget(self.ch15, 7, 1, 1, 1)
        self.gridLayout_5.addLayout(self.chLayout, 0, 0, 9, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.graphBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.yButton = QtGui.QPushButton(self.graphBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yButton.sizePolicy().hasHeightForWidth())
        self.yButton.setSizePolicy(sizePolicy)
        self.yButton.setMinimumSize(QtCore.QSize(150, 0))
        self.yButton.setObjectName(_fromUtf8("yButton"))
        self.horizontalLayout_7.addWidget(self.yButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.graphBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.xButton = QtGui.QPushButton(self.graphBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xButton.sizePolicy().hasHeightForWidth())
        self.xButton.setSizePolicy(sizePolicy)
        self.xButton.setMinimumSize(QtCore.QSize(150, 0))
        self.xButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xButton.setObjectName(_fromUtf8("xButton"))
        self.horizontalLayout_5.addWidget(self.xButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 2, 2, 2)
        self.autoDrawCB = QtGui.QCheckBox(self.graphBox)
        self.autoDrawCB.setEnabled(False)
        self.autoDrawCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.autoDrawCB.setChecked(False)
        self.autoDrawCB.setObjectName(_fromUtf8("autoDrawCB"))
        self.gridLayout_5.addWidget(self.autoDrawCB, 5, 3, 1, 1)
        self.showLineCB = QtGui.QCheckBox(self.graphBox)
        self.showLineCB.setEnabled(True)
        self.showLineCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showLineCB.setObjectName(_fromUtf8("showLineCB"))
        self.gridLayout_5.addWidget(self.showLineCB, 3, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 2, 4, 2, 1)
        self.showLegendCB = QtGui.QCheckBox(self.graphBox)
        self.showLegendCB.setEnabled(True)
        self.showLegendCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showLegendCB.setChecked(False)
        self.showLegendCB.setObjectName(_fromUtf8("showLegendCB"))
        self.gridLayout_5.addWidget(self.showLegendCB, 4, 3, 1, 1)
        self.gridLayout_8.addWidget(self.graphBox, 3, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.statusTab = QtGui.QWidget()
        self.statusTab.setObjectName(_fromUtf8("statusTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.statusTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.statusTable = QtGui.QTableWidget(self.statusTab)
        self.statusTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.statusTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.statusTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.statusTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.statusTable.setObjectName(_fromUtf8("statusTable"))
        self.statusTable.setColumnCount(5)
        self.statusTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(4, item)
        self.statusTable.horizontalHeader().setCascadingSectionResizes(True)
        self.statusTable.horizontalHeader().setDefaultSectionSize(140)
        self.statusTable.horizontalHeader().setMinimumSectionSize(40)
        self.statusTable.horizontalHeader().setStretchLastSection(True)
        self.statusTable.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.statusTable, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.addStatButton = QtGui.QToolButton(self.statusTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStatButton.sizePolicy().hasHeightForWidth())
        self.addStatButton.setSizePolicy(sizePolicy)
        self.addStatButton.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addStatButton.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.addStatButton.setIcon(icon)
        self.addStatButton.setObjectName(_fromUtf8("addStatButton"))
        self.verticalLayout_4.addWidget(self.addStatButton)
        self.removeStatButton = QtGui.QToolButton(self.statusTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeStatButton.sizePolicy().hasHeightForWidth())
        self.removeStatButton.setSizePolicy(sizePolicy)
        self.removeStatButton.setMinimumSize(QtCore.QSize(40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.removeStatButton.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removeStatButton.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.removeStatButton.setIcon(icon)
        self.removeStatButton.setObjectName(_fromUtf8("removeStatButton"))
        self.verticalLayout_4.addWidget(self.removeStatButton)
        spacerItem16 = QtGui.QSpacerItem(20, 429, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.updateStatusButton = QtGui.QPushButton(self.statusTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateStatusButton.sizePolicy().hasHeightForWidth())
        self.updateStatusButton.setSizePolicy(sizePolicy)
        self.updateStatusButton.setObjectName(_fromUtf8("updateStatusButton"))
        self.horizontalLayout_15.addWidget(self.updateStatusButton)
        spacerItem17 = QtGui.QSpacerItem(825, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 1, 0, 1, 2)
        self.tabWidget.addTab(self.statusTab, _fromUtf8(""))
        self.messageBox = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageBox.sizePolicy().hasHeightForWidth())
        self.messageBox.setSizePolicy(sizePolicy)
        self.messageBox.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.messageBox.setFont(font)
        self.messageBox.setAcceptDrops(False)
        self.messageBox.setAutoFillBackground(False)
        self.messageBox.setFrameShape(QtGui.QFrame.WinPanel)
        self.messageBox.setFrameShadow(QtGui.QFrame.Raised)
        self.messageBox.setAutoFormatting(QtGui.QTextEdit.AutoNone)
        self.messageBox.setDocumentTitle(_fromUtf8(""))
        self.messageBox.setUndoRedoEnabled(False)
        self.messageBox.setReadOnly(True)
        self.messageBox.setObjectName(_fromUtf8("messageBox"))
        self.gridLayout_9.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSettingd = QtGui.QAction(MainWindow)
        self.actionSettingd.setObjectName(_fromUtf8("actionSettingd"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionGuide = QtGui.QAction(MainWindow)
        self.actionGuide.setObjectName(_fromUtf8("actionGuide"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.label.setBuddy(self.localIPBox)
        self.label_2.setBuddy(self.localPortBox)
        self.label_3.setBuddy(self.targetIPBox)
        self.label_4.setBuddy(self.targetPortBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.localIPBox)
        MainWindow.setTabOrder(self.localIPBox, self.localPortBox)
        MainWindow.setTabOrder(self.localPortBox, self.targetIPBox)
        MainWindow.setTabOrder(self.targetIPBox, self.targetPortBox)
        MainWindow.setTabOrder(self.targetPortBox, self.connectButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sniper", None))
        self.groupBox.setTitle(_translate("MainWindow", "Local Host:", None))
        self.label.setText(_translate("MainWindow", "Local IP:", None))
        self.localIPBox.setInputMask(_translate("MainWindow", "000.000.000.000; ", None))
        self.label_2.setText(_translate("MainWindow", "Port:", None))
        self.localPortBox.setInputMask(_translate("MainWindow", "00000; ", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Target:", None))
        self.label_3.setText(_translate("MainWindow", "Target IP:", None))
        self.targetIPBox.setInputMask(_translate("MainWindow", "000.000.000.000; ", None))
        self.label_4.setText(_translate("MainWindow", "Port:", None))
        self.targetPortBox.setInputMask(_translate("MainWindow", "00000; ", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connectionTab), _translate("MainWindow", "Connection", None))
        self.addButton.setToolTip(_translate("MainWindow", "Add New Row", None))
        self.addButton.setText(_translate("MainWindow", "+", None))
        self.loadCfgButton.setText(_translate("MainWindow", "Load cfg File", None))
        self.saveCfgButton.setText(_translate("MainWindow", "Save cfg File", None))
        self.sendButton.setText(_translate("MainWindow", "Send to Board", None))
        self.configFileLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.removeButton.setToolTip(_translate("MainWindow", "Remove Selected Row", None))
        self.removeButton.setText(_translate("MainWindow", "-", None))
        self.clearButton.setToolTip(_translate("MainWindow", "Clear All", None))
        self.clearButton.setText(_translate("MainWindow", "C", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlTab), _translate("MainWindow", "Config", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Capture and Trigger :", None))
        self.label_9.setText(_translate("MainWindow", "Trigger Type:", None))
        self.triggerButton.setText(_translate("MainWindow", "trigger", None))
        self.label_15.setText(_translate("MainWindow", "Trigger Numbers:", None))
        self.numTriggerBox.setText(_translate("MainWindow", "1", None))
        self.label_7.setText(_translate("MainWindow", "Capture Buffer:", None))
        self.captureButton.setText(_translate("MainWindow", "OFF", None))
        self.sendTriggerButton.setText(_translate("MainWindow", "SendSwTrigger", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Monitor:", None))
        self.clearBufferButton.setText(_translate("MainWindow", "Clear Buffer", None))
        self.label_14.setText(_translate("MainWindow", "Current File:", None))
        self.label_13.setText(_translate("MainWindow", "Event Buffer:", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data File:", None))
        self.label_10.setText(_translate("MainWindow", "File Tag:", None))
        self.label_11.setText(_translate("MainWindow", "TriggerPerFile:", None))
        self.autoSaveCB.setText(_translate("MainWindow", "AutoSave", None))
        self.label_8.setText(_translate("MainWindow", "Save to disk:", None))
        self.startButton.setText(_translate("MainWindow", "OFF", None))
        self.chDirButton.setText(_translate("MainWindow", "Change Dir", None))
        self.clearDataButton.setText(_translate("MainWindow", "Clear Data", None))
        self.chFileButton.setText(_translate("MainWindow", "Save As", None))
        self.filenameLabel.setText(_translate("MainWindow", "filename", None))
        self.calibCB.setText(_translate("MainWindow", "Calibration:", None))
        self.cFileButton.setText(_translate("MainWindow", "Select File", None))
        self.cFileLabel.setText(_translate("MainWindow", "filename", None))
        self.graphBox.setTitle(_translate("MainWindow", "Graph:", None))
        self.drawButton.setText(_translate("MainWindow", "Draw", None))
        self.browseButton.setText(_translate("MainWindow", "Browse", None))
        self.showMarkCB.setText(_translate("MainWindow", "Show Markers", None))
        self.allONButton.setText(_translate("MainWindow", "ALL ON", None))
        self.allOFFButton.setText(_translate("MainWindow", "ALL OFF", None))
        self.ch10.setText(_translate("MainWindow", "CH10", None))
        self.ch0.setText(_translate("MainWindow", "CH0", None))
        self.ch8.setText(_translate("MainWindow", "CH8", None))
        self.ch1.setText(_translate("MainWindow", "CH1", None))
        self.ch9.setText(_translate("MainWindow", "CH9", None))
        self.ch2.setText(_translate("MainWindow", "CH2", None))
        self.ch3.setText(_translate("MainWindow", "CH3", None))
        self.ch11.setText(_translate("MainWindow", "CH11", None))
        self.ch4.setText(_translate("MainWindow", "CH4", None))
        self.ch12.setText(_translate("MainWindow", "CH12", None))
        self.ch5.setText(_translate("MainWindow", "CH5", None))
        self.ch13.setText(_translate("MainWindow", "CH13", None))
        self.ch6.setText(_translate("MainWindow", "CH6", None))
        self.ch14.setText(_translate("MainWindow", "CH14", None))
        self.ch7.setText(_translate("MainWindow", "CH7", None))
        self.ch15.setText(_translate("MainWindow", "CH15", None))
        self.label_6.setText(_translate("MainWindow", "Y:", None))
        self.yButton.setText(_translate("MainWindow", "yValue", None))
        self.label_5.setText(_translate("MainWindow", "X:", None))
        self.xButton.setText(_translate("MainWindow", "xValue", None))
        self.autoDrawCB.setText(_translate("MainWindow", "Auto Draw", None))
        self.showLineCB.setText(_translate("MainWindow", "Show Line", None))
        self.showLegendCB.setText(_translate("MainWindow", "Show Legend", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("MainWindow", "Data", None))
        item = self.statusTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESCRIPTION", None))
        item = self.statusTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ADDRESS", None))
        item = self.statusTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "VALUE(HEX)", None))
        item = self.statusTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VALUE(DEC)", None))
        item = self.statusTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "VALUE(BIN)", None))
        self.addStatButton.setToolTip(_translate("MainWindow", "Add New Row", None))
        self.addStatButton.setText(_translate("MainWindow", "+", None))
        self.removeStatButton.setToolTip(_translate("MainWindow", "Remove Selected Row", None))
        self.removeStatButton.setText(_translate("MainWindow", "-", None))
        self.updateStatusButton.setText(_translate("MainWindow", "Update Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statusTab), _translate("MainWindow", "Status", None))
        self.actionSettingd.setText(_translate("MainWindow", "Settings", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionGuide.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

