# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sniperGui.ui'
#
# Created: Sun Sep  1 16:57:28 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(735, 767)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 300))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.connectionTab = QtGui.QWidget()
        self.connectionTab.setObjectName(_fromUtf8("connectionTab"))
        self.gridLayout = QtGui.QGridLayout(self.connectionTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.localIPBox = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localIPBox.sizePolicy().hasHeightForWidth())
        self.localIPBox.setSizePolicy(sizePolicy)
        self.localIPBox.setMinimumSize(QtCore.QSize(200, 0))
        self.localIPBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.localIPBox.setObjectName(_fromUtf8("localIPBox"))
        self.horizontalLayout_2.addWidget(self.localIPBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.localPortBox = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localPortBox.sizePolicy().hasHeightForWidth())
        self.localPortBox.setSizePolicy(sizePolicy)
        self.localPortBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.localPortBox.setObjectName(_fromUtf8("localPortBox"))
        self.horizontalLayout_2.addWidget(self.localPortBox)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(232, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(450, 100))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.targetIPBox = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetIPBox.sizePolicy().hasHeightForWidth())
        self.targetIPBox.setSizePolicy(sizePolicy)
        self.targetIPBox.setMinimumSize(QtCore.QSize(200, 0))
        self.targetIPBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.targetIPBox.setObjectName(_fromUtf8("targetIPBox"))
        self.horizontalLayout_3.addWidget(self.targetIPBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.targetPortBox = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetPortBox.sizePolicy().hasHeightForWidth())
        self.targetPortBox.setSizePolicy(sizePolicy)
        self.targetPortBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.targetPortBox.setObjectName(_fromUtf8("targetPortBox"))
        self.horizontalLayout_3.addWidget(self.targetPortBox)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(232, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.connectButton = QtGui.QPushButton(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(100, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("network-wired"))
        self.connectButton.setIcon(icon)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 2, 0, 1, 1)
        self.disconnectButton = QtGui.QPushButton(self.connectionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        self.disconnectButton.setMinimumSize(QtCore.QSize(100, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("network-offline"))
        self.disconnectButton.setIcon(icon)
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.gridLayout.addWidget(self.disconnectButton, 2, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(233, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 256, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 2, 1, 1)
        self.tabWidget.addTab(self.connectionTab, _fromUtf8(""))
        self.controlTab = QtGui.QWidget()
        self.controlTab.setEnabled(False)
        self.controlTab.setObjectName(_fromUtf8("controlTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.controlTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.controlTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.triggerButton = QtGui.QPushButton(self.controlTab)
        self.triggerButton.setObjectName(_fromUtf8("triggerButton"))
        self.horizontalLayout_4.addWidget(self.triggerButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(421, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 1, 2)
        self.configView = QtGui.QTableView(self.controlTab)
        self.configView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.configView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.configView.setSortingEnabled(True)
        self.configView.setCornerButtonEnabled(False)
        self.configView.setObjectName(_fromUtf8("configView"))
        self.configView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.configView, 1, 0, 4, 5)
        self.addButton = QtGui.QToolButton(self.controlTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.addButton.setIcon(icon)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout_2.addWidget(self.addButton, 1, 5, 1, 1)
        self.removeButton = QtGui.QToolButton(self.controlTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.removeButton.setIcon(icon)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.gridLayout_2.addWidget(self.removeButton, 2, 5, 1, 1)
        self.clearButton = QtGui.QToolButton(self.controlTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.clearButton.setIcon(icon)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.gridLayout_2.addWidget(self.clearButton, 3, 5, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 288, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 4, 5, 1, 1)
        self.loadCfgButton = QtGui.QPushButton(self.controlTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.loadCfgButton.setIcon(icon)
        self.loadCfgButton.setObjectName(_fromUtf8("loadCfgButton"))
        self.gridLayout_2.addWidget(self.loadCfgButton, 5, 0, 1, 1)
        self.saveCfgButton = QtGui.QPushButton(self.controlTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.saveCfgButton.setIcon(icon)
        self.saveCfgButton.setObjectName(_fromUtf8("saveCfgButton"))
        self.gridLayout_2.addWidget(self.saveCfgButton, 5, 1, 1, 2)
        spacerItem8 = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 5, 3, 1, 1)
        self.sendButton = QtGui.QPushButton(self.controlTab)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-send"))
        self.sendButton.setIcon(icon)
        self.sendButton.setObjectName(_fromUtf8("sendButton"))
        self.gridLayout_2.addWidget(self.sendButton, 5, 4, 1, 2)
        self.tabWidget.addTab(self.controlTab, _fromUtf8(""))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setEnabled(False)
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.tabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.messageBox = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.messageBox.sizePolicy().hasHeightForWidth())
        self.messageBox.setSizePolicy(sizePolicy)
        self.messageBox.setMinimumSize(QtCore.QSize(0, 100))
        self.messageBox.setObjectName(_fromUtf8("messageBox"))
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettingd = QtGui.QAction(MainWindow)
        self.actionSettingd.setObjectName(_fromUtf8("actionSettingd"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionGuide = QtGui.QAction(MainWindow)
        self.actionGuide.setObjectName(_fromUtf8("actionGuide"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionSettingd)
        self.menuFile.addAction(self.actionClose)
        self.menu.addAction(self.actionGuide)
        self.menu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.label.setBuddy(self.localIPBox)
        self.label_2.setBuddy(self.localPortBox)
        self.label_3.setBuddy(self.targetIPBox)
        self.label_4.setBuddy(self.targetPortBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.localIPBox)
        MainWindow.setTabOrder(self.localIPBox, self.localPortBox)
        MainWindow.setTabOrder(self.localPortBox, self.targetIPBox)
        MainWindow.setTabOrder(self.targetIPBox, self.targetPortBox)
        MainWindow.setTabOrder(self.targetPortBox, self.connectButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sniper", None))
        self.groupBox.setTitle(_translate("MainWindow", "Local Host:", None))
        self.label.setText(_translate("MainWindow", "Local IP:", None))
        self.localIPBox.setInputMask(_translate("MainWindow", "000.000.000.000; ", None))
        self.label_2.setText(_translate("MainWindow", "Port:", None))
        self.localPortBox.setInputMask(_translate("MainWindow", "00000; ", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Target:", None))
        self.label_3.setText(_translate("MainWindow", "Target IP:", None))
        self.targetIPBox.setInputMask(_translate("MainWindow", "000.000.000.000; ", None))
        self.label_4.setText(_translate("MainWindow", "Port:", None))
        self.targetPortBox.setInputMask(_translate("MainWindow", "00000; ", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connectionTab), _translate("MainWindow", "Connection", None))
        self.label_5.setText(_translate("MainWindow", "Trigger Type:", None))
        self.triggerButton.setText(_translate("MainWindow", "trigger", None))
        self.addButton.setToolTip(_translate("MainWindow", "Add New Row", None))
        self.addButton.setText(_translate("MainWindow", "...", None))
        self.removeButton.setToolTip(_translate("MainWindow", "Remove Selected Row", None))
        self.removeButton.setText(_translate("MainWindow", "...", None))
        self.clearButton.setToolTip(_translate("MainWindow", "Clear All", None))
        self.clearButton.setText(_translate("MainWindow", "...", None))
        self.loadCfgButton.setText(_translate("MainWindow", "Load cfg File", None))
        self.saveCfgButton.setText(_translate("MainWindow", "Save cfg File", None))
        self.sendButton.setText(_translate("MainWindow", "Send to Board", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlTab), _translate("MainWindow", "Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("MainWindow", "Data Fetching", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menu.setTitle(_translate("MainWindow", "?", None))
        self.actionSettingd.setText(_translate("MainWindow", "Settings", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionGuide.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

